---
- name : "Get the deployed stack"
  hosts: localhost
  gather_facts: yes
  vars:
    stack_name: "{{lookup('env','STACK_NAME')}}"
  tasks:
    - cloudformation_facts:
        stack_name: "{{stack_name}}"
      register: ecs_stack
    - name: Display the alb
      debug: 
        msg:
          - "{{ ansible_facts.cloudformation[stack_name].stack_outputs.ECSALB }}"
    - name: Validate the ALB DNS
      uri: 
        url: "http://{{ ansible_facts.cloudformation[stack_name].stack_outputs.ECSALB }}/health"
        method: GET
        status_code: 200
        return_content: yes
      register: ecsalb_return_value
      failed_when: ecsalb_return_value.json.status != "UP"
    - name: Display the alb response
      debug: 
        msg:
          - "{{ecsalb_return_value}}"

